global:
  scrape_interval: 5s   # every 5 seconds we'll collect metrics

scrape_configs:
  - job_name: 'tasks-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['tasks-api:8080']
        labels:
          service: "tasks-api"
